---
 - name: setup mysql database for wordpress
   mysql_db: name={{wordpress.dbname}} state=present

 - name: setup mysql user for wordpress
   mysql_user: name={{wordpress.dbuser}} password={{wordpress.dbpass}} priv=*.*:ALL,GRANT state=present

 - name: download wordpress source file
   get_url: url={{wordpress.src_uri}} dest=/tmp/wp.tar.gz mode=0666

 - name: unarchive wordpress source file
   command: tar zxvf /tmp/wp.tar.gz chdir=/var/

 - name: setting permission of wordpress directory
   file: path=/var/wordpress owner=www-data group=www-data mode=0700 recurse=yes state=directory

 - name: create directory for self certficate 
   file: path=/etc/ssl/self-signed/ owner=root group=root mode=0700 state=directory

 - name: carete self certficate and key 
   shell: |
      crt_file="/etc/ssl/self-signed/{{ hostname }}.crt" &&
      key_file="/etc/ssl/self-signed/{{ hostname }}.key" &&
      subject="/C=JP/ST=Fukuoka/L=Fukuoka City/CN={{ hostname }}" &&
      openssl req -new -newkey rsa:2048 -sha1 -x509 -nodes \
        -set_serial 1 \
        -days 365 \
        -subj "$subject" \
        -out "$crt_file" \
        -keyout "$key_file" 

 - name: upload apache configuration file
   template: src=wordpress.conf dest=/etc/apache2/sites-available/wordpress.conf

 - name: enable wordpress config 
   command: a2ensite wordpress

 - name: restart apache2
   service: name=apache2 state=restarted

 - name: upload wordpress configuration file
   template: src=wp-config.php dest=/var/wordpress/wp-config.php

