---
 - name: iptables.ruleをアップロードする
   copy: src=iptables.rule dest=/etc/iptables.rule group=root owner=root mode=0600

 - name: iptables.ruleを適用する
   command: sh -c "iptables-restore /etc/iptables.rule"

 - name: 再起動後もiptables.ruleを適用する
   copy: src=iptables_start dest=/etc/network/if-pre-up.d/iptables_start group=root owner=root mode=700 


